<a href="https://colab.research.google.com/github/rsurendraidexcel/aiml-labs/blob/main/torch_basic_ipyb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import random
import torchvision

In [ ]:
x = torch.Tensor(3,2,4,5)

In [ ]:
type(x)

torch.Tensor

In [ ]:
x.size()

torch.Size([3, 2, 4, 5])

In [ ]:
print(x)

tensor([[[[ 2.6780e-36,  4.5744e-41,  2.6780e-36,  4.5744e-41,  1.4945e-33],
          [ 0.0000e+00,  1.4945e-33,  0.0000e+00,  1.4013e-45,  0.0000e+00],
          [ 1.4946e-33,  0.0000e+00,  1.4013e-45,  0.0000e+00,  1.4945e-33],
          [ 0.0000e+00,  3.3631e-44,  0.0000e+00,  1.4352e-36,  4.5744e-41]],

         [[ 2.8026e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.4013e-45],
          [ 0.0000e+00,  1.4013e-45,  1.4013e-45,  3.3631e-44,  0.0000e+00],
          [-6.2196e+07,  4.5743e-41,  1.4013e-45,  4.5743e-41,  1.4013e-45],
          [ 1.1815e+22,  1.4013e-45,  5.6052e-45,  1.4013e-45,  1.2612e-44]]],


        [[[ 2.9427e-44,  4.5743e-41,  1.4945e-33,  0.0000e+00, -1.9791e+08],
          [ 4.5743e-41,  1.4013e-45,  0.0000e+00,  1.4013e-45,  5.6052e-45],
          [ 1.4013e-45,  2.2421e-44,  5.6052e-45,  0.0000e+00,  1.4945e-33],
          [ 0.0000e+00,  1.4945e-33,  0.0000e+00,  1.4945e-33,  0.0000e+00]],

         [[ 1.4945e-33,  0.0000e+00,  2.8026e-44,  1.4013e-45,  1.44

In [ ]:
print(torch.__version__)

2.0.0+cu118


In [ ]:
#example

py_list = [[2.3,4.5,3.5],[8.2,4.5,3.5],[8.4,5.4,4.5]]

In [ ]:
print(py_list)

[[2.3, 4.5, 3.5], [8.2, 4.5, 3.5], [8.4, 5.4, 4.5]]


In [ ]:
type(py_list)

list

In [ ]:
pt_tensor_list = torch.FloatTensor(py_list)

In [ ]:
type(pt_tensor_list)

torch.Tensor

In [ ]:

print(pt_tensor_list)

tensor([[2.3000, 4.5000, 3.5000],
        [8.2000, 4.5000, 3.5000],
        [8.4000, 5.4000, 4.5000]])


In [ ]:
#Relu Activation fuction 
relu1 = nn.ReLU(inplace=False)

In [ ]:
model = nn.Sequential()

In [ ]:
first_conv_layer =  nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, stride=1, padding=1)
model.add_module("conv1", first_conv_layer)
model.add_module("Relu1", relu1)
second_conv_layer =  nn.Conv2d(in_channels=16, out_channels=32, kernel_size=[3,3], stride=[1,1], padding=[1,1])
model.add_module("conv2", second_conv_layer)
model.add_module("Relu2",  nn.ReLU(inplace=False))

In [ ]:
#Activation fuction

def activation(x):
  return 1/(1+torch.exp(-x))

In [ ]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)

# and a true bias term
bias = torch.randn((1, 1))

In [ ]:
### Solution
# Now, make our labels from our data and true weights
y = activation(torch.sum(features * weights) + bias)
y1 = activation((features * weights).sum() + bias)

In [ ]:
## Solution

y3 = activation(torch.mm(features, weights.view(5,1)) + bias)

In [ ]:
print(weights.shape)
print(weights.size())
print(type(weights))

torch.Size([1, 5])
torch.Size([1, 5])
<class 'torch.Tensor'>


In [ ]:
import numpy as np
a = np.random.rand(4,3)

In [ ]:
b = torch.from_numpy(a)
type(b)

torch.Tensor

In [ ]:
b

tensor([[0.8217, 0.9907, 0.5106],
        [0.7384, 0.9147, 0.2563],
        [0.4997, 0.5224, 0.5700],
        [0.5198, 0.4265, 0.9962]], dtype=torch.float64)

In [ ]:
a

array([[0.82170418, 0.99071311, 0.51058781],
       [0.73841673, 0.91468401, 0.2563129 ],
       [0.49972129, 0.52237117, 0.57003848],
       [0.51979796, 0.42654128, 0.99624975]])

In [ ]:
b.numpy()

array([[0.82170418, 0.99071311, 0.51058781],
       [0.73841673, 0.91468401, 0.2563129 ],
       [0.49972129, 0.52237117, 0.57003848],
       [0.51979796, 0.42654128, 0.99624975]])

In [ ]:
# Multiply PyTorch Tensor by 3, in place
b.mul_(3)

tensor([[14.7907, 17.8328,  9.1906],
        [13.2915, 16.4643,  4.6136],
        [ 8.9950,  9.4027, 10.2607],
        [ 9.3564,  7.6777, 17.9325]], dtype=torch.float64)